services:
  auth:
    container_name: auth-container
    depends_on:
      postgresql:
        condition: service_healthy
    build: ../../auth/
    environment:
      APPLICATION_PORT: 6969
      DATA_SOURCE_URL: "postgresql://postgres:s3cr3t@postgres-container:5432/auth"
  postgresql:
    container_name: postgres-container
    image: "postgres:15.2"
    ports:
      - "5432:5432"
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "s3cr3t"
      POSTGRES_DB: "auth"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  pgdata:
